fallback: Handle GetNextVariableName returning EFI_BUFFER_TOO_SMALL
rhboot/shim pull request #358
Opened 2021-04-06 03:26 UTC by jprvita

Now that fallback lists all EFI variables instead of only `Boot????` variables, a 256 chars buffer may not be large enough for the variable's name. This PR changes it to a dynamic buffer that starts with 256 chars, but gets extended if needed. It also adds extra logs when `GetNextVariableName` returns an error.

This is a follow-up to #312 -- these changes were mixed with other downstream commits and were left behind.

2021-04-09 19:33 UTC, jprvita commented
For-pushed rebase on latest main.

2021-04-12 22:56 UTC, jprvita commented
Force-pushed rebase on latest main.

2021-06-01 18:11 UTC, jprvita commented
Force-pushed rebase on latest main.

2021-07-15 23:04 UTC, vathpela requested changes
A couple of minor nits, but this basically looks good to me.

2021-07-15 23:04 UTC, vathpela commented on fallback.c
> +					     L"name\n");
Don't break the string across lines here.

2021-07-15 23:04 UTC, vathpela commented on fallback.c
> +					     L"hardware error\n");
Don't break the string across lines here.

2021-07-15 23:04 UTC, vathpela commented on fallback.c
> +					     L"varname_size=%d, varname=%s\n",
Don't break the string across lines here.

2021-07-15 23:04 UTC, vathpela commented on fallback.c
> +					     L" chars long and retrying\n",
Don't break the string across lines here (even though it was incorrectly broken before.)

2021-09-03 20:52 UTC, vathpela commented
I've pushed this as 437caecbab1 and 77648c5c01c .

2021-09-03 20:52 UTC, closed without merging