pe: simplify generate_hash()
rhboot/shim pull request #411
Opened 2021-09-03 20:47 UTC by xypron

Copying the value of datasize_in to two further variables and then using
all three randomly in the code makes it hard to read.

datasize_in is never changed in generate_hash() so we can do with this
parameter alone. Let's declare it as const to verify that its value
is invariant.

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>

2021-09-06 16:22 UTC, xnox commented
Given that there is no "datasize_out" and that most of the function code uses "datasize" maybe it's better to rename the function argument to "datasize" and then drop all references to "size" and "datasize_in"? this should make the diff smaller, no?

2021-09-08 15:43 UTC, xypron commented
@xnox: Thank you for reviewing. I will update the patch and force push it.

2021-09-08 16:04 UTC, xypron commented
@xnox: I have update the patch according to your recommendation. Please, review again.

2021-09-08 16:49 UTC, xypron commented
Rebased on current origin/main

2021-09-10 14:26 UTC, frozencemetery requested changes
While the rest of the code is fine, I don't think making the function parameter const increases readability, or really gains anything.  If anything, it's unusual enough that it makes the function harder to read in my opinion.

Code seems fine otherwise.

2021-09-10 15:19 UTC, xypron commented
@frozencemetery: thank you for reviewing. I removed const and force pushed to corrected patch.

2021-09-10 15:48 UTC, frozencemetery approved these changes
Thanks, I'm happy with this.

2021-09-10 20:09 UTC, merged