Make the names of EFI binaries arch-independent
rhboot/shim pull request #520
Opened 2022-10-24 04:10 UTC by dennis-tseng99

Since we only build the 64-bit binaries, we don't have the issue of the mixed architecture binaries in the same directory. Besides, we will use the same install script for x86_64 and AArch64. It's easier to maintain the script with the same names.

Signed-off-by: Gary Lin <glin@suse.com>
Signed-off-by: Dennis Tseng <dennis.tseng@suse.com>

2022-10-24 07:32 UTC, julian-klode commented
There's plenty of folks building 32-bit ones.

2022-10-25 08:35 UTC, dennis-tseng99 commented
@julian-klode 
Thanks for your comment. I added a compiled flag(ARCH_INDEPEND) in Makefile, shim.h, shim.c and fallback.c to let user make his/her final decision.

2022-10-25 16:37 UTC, frozencemetery requested changes
Adds a configuration option, -1.

2022-10-25 16:55 UTC, julian-klode commented
I think what we could do is try arch specific first and then the independent ones. But also I'd prefer not to have arch-independent shim binary named out there.

The moment you do it, product managers will appear and request an installer  image that runs on both amd64 and arm64.😜

2022-10-25 17:44 UTC, steve-mcintyre commented
> I think what we could do is try arch specific first and then the independent ones. But also I'd prefer not to have arch-independent shim binary named out there.
> 
> The moment you do it, product managers will appear and request an installer image that runs on both amd64 and arm64.stuck_out_tongue_winking_eye

Agreed - this is a really bad mistake IMHO.

2022-11-11 15:01 UTC, julian-klode commented
I think we're going to close this as we don't want this as there's lots of opposition here.

2022-11-11 15:01 UTC, closed without merging